name: RSS

on:
  schedule:
    - cron: '*/5 * * * *' # 每一分鐘執行一次

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 # 使用 checkout 動作來取得 repo 的內容

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet # 安裝 xmlstarlet 工具，用來處理 XML 檔案

      - name: Fetch RSS feeds
        run: | # 使用多行指令來取得 RSS feeds 並存成 XML 檔案
          curl https://news.pts.org.tw/xml/newsfeed.xml > feeds/公共電視_公視新聞.xml
          curl https://www.peopo.org/rss-news > feeds/PeoPo公民新聞_最新報導10則.xml
          curl https://www.peopo.org/rss-top10 > feeds/PeoPo公民新聞_本日推薦10則.xml
          curl https://rthk.hk/rthk/news/rss/c_expressnews_clocal.xml > feeds/香港電台新聞網_本地新聞.xml
          curl https://rthk.hk/rthk/news/rss/c_expressnews_greaterchina.xml > feeds/香港電台新聞網_大中華新聞.xml

      - name: Format RSS feeds
        run: | # 使用多行指令來格式化 RSS feeds 的 XML 檔案，讓它們更容易閱讀
          xmlstarlet fo -s 2 feeds/公共電視_公視新聞.xml > feeds/公共電視_公視新聞_formatted.xml
          xmlstarlet fo -s 2 feeds/PeoPo公民新聞_最新報導10則.xml > feeds/PeoPo公民新聞_最新報導10則_formatted.xml
          xmlstarlet fo -s 2 feeds/PeoPo公民新聞_本日推薦10則.xml > feeds/PeoPo公民新聞_本日推薦10則_formatted.xml
          xmlstarlet fo -s 2 feeds/香港電台新聞網_本地新聞.xml > feeds/香港電台新聞網_本地新聞_formatted.xml
          xmlstarlet fo -s 2 feeds/香港電台新聞網_大中華新聞.xml > feeds/香港電台新聞網_大中華新聞_formatted.xml

      - name: Upload RSS feeds
        uses: actions/upload-artifact@v2 # 使用 upload-artifact 動作來上傳 RSS feeds 的 XML 檔案到 repo 裡
        with:
          name: feeds
          path: feeds/*.xml
